import { POST_PRANDIAL_PLASMA_GLUCOSE_2_HOURS_AFTER_LUNCH_FORM } from "@/availableTests/POST_PRANDIAL_PLASMA_GLUCOSE_2_HOURS_AFTER_LUNCH/components/form";
import { SavedReport } from "@/availableTests/POST_PRANDIAL_PLASMA_GLUCOSE_2_HOURS_AFTER_LUNCH/components/report";
import { type POST_PRANDIAL_PLASMA_GLUCOSE_2_HOURS_AFTER_LUNCH_TYPE } from "@availableTests/POST_PRANDIAL_PLASMA_GLUCOSE_2_HOURS_AFTER_LUNCH/type";
import { EXAMPLES } from "@availableTests/POST_PRANDIAL_PLASMA_GLUCOSE_2_HOURS_AFTER_LUNCH/examples";
import { actions } from "@availableTests/POST_PRANDIAL_PLASMA_GLUCOSE_2_HOURS_AFTER_LUNCH/actions";

export {
  type POST_PRANDIAL_PLASMA_GLUCOSE_2_HOURS_AFTER_LUNCH_TYPE,
  POST_PRANDIAL_PLASMA_GLUCOSE_2_HOURS_AFTER_LUNCH_FORM,
  SavedReport,
  EXAMPLES,
  actions,
};
