import { POST_PRANDIAL_PLASMA_GLUCOSE_2_HOURS_AFTER_BREAKFAST_FORM } from "@/availableTests/POST_PRANDIAL_PLASMA_GLUCOSE_2_HOURS_AFTER_BREAKFAST/components/form";
import { SavedReport } from "@/availableTests/POST_PRANDIAL_PLASMA_GLUCOSE_2_HOURS_AFTER_BREAKFAST/components/report";
import { type POST_PRANDIAL_PLASMA_GLUCOSE_2_HOURS_AFTER_BREAKFAST_TYPE } from "@availableTests/POST_PRANDIAL_PLASMA_GLUCOSE_2_HOURS_AFTER_BREAKFAST/type";
import { EXAMPLES } from "@availableTests/POST_PRANDIAL_PLASMA_GLUCOSE_2_HOURS_AFTER_BREAKFAST/examples";
import { actions } from "@availableTests/POST_PRANDIAL_PLASMA_GLUCOSE_2_HOURS_AFTER_BREAKFAST/actions";

export {
  type POST_PRANDIAL_PLASMA_GLUCOSE_2_HOURS_AFTER_BREAKFAST_TYPE,
  POST_PRANDIAL_PLASMA_GLUCOSE_2_HOURS_AFTER_BREAKFAST_FORM,
  SavedReport,
  EXAMPLES,
  actions,
};
