import { POST_PRANDIAL_PLASMA_GLUCOSE_2_HOURS_AFTER_DINNER_FORM } from "@/availableTests/POST_PRANDIAL_PLASMA_GLUCOSE_2_HOURS_AFTER_DINNER/components/form";
import { SavedReport } from "@/availableTests/POST_PRANDIAL_PLASMA_GLUCOSE_2_HOURS_AFTER_DINNER/components/report";
import { type POST_PRANDIAL_PLASMA_GLUCOSE_2_HOURS_AFTER_DINNER_TYPE } from "@availableTests/POST_PRANDIAL_PLASMA_GLUCOSE_2_HOURS_AFTER_DINNER/type";
import { EXAMPLES } from "@availableTests/POST_PRANDIAL_PLASMA_GLUCOSE_2_HOURS_AFTER_DINNER/examples";
import { actions } from "@availableTests/POST_PRANDIAL_PLASMA_GLUCOSE_2_HOURS_AFTER_DINNER/actions";

export {
  type POST_PRANDIAL_PLASMA_GLUCOSE_2_HOURS_AFTER_DINNER_TYPE,
  POST_PRANDIAL_PLASMA_GLUCOSE_2_HOURS_AFTER_DINNER_FORM,
  SavedReport,
  EXAMPLES,
  actions,
};
